# Change these first
owner: ayphu # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Ayphu
    url: https://ayphu.com
  - name: Panel de control
    url: https://app.ayphu.com
  - name: Documentación
    url: https://docs.ayphu.com

assignees:
  - luisgagocasas
  - oscarhugopaz
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ayphu.com
  # baseUrl: /your-repo-name
  logoUrl: https://landing.lagc-peru.com/wp-content/uploads/ayphu-favicon.png
  favicon: https://landing.lagc-peru.com/wp-content/uploads/ayphu-favicon.png
  themeUrl: https://status.ayphu.com/style.css
  name: Página de status
  introTitle: "Esta es la página del status de los servicios de Ayphu"
  introMessage: En esta página podrás ver el status de los diferentes servicios de Ayphu como el panel de control, la documentación, etc.
  navbar:
    - title: Ayphu
      href: https://ayphu.com

i18n:
  activeIncidents: Incidentes activos
  allSystemsOperational: Todos los sistemas están operativos
  incidentReport: "Incidente #$NUMBER reporte →"
  activeIncidentSummary: Abierto el $DATE con $POSTS publicaciones
  incidentTitle: Detalles del incidente $NUMBER
  incidentDetails: Detalles del incidente
  incidentFixed: Solucionado
  incidentOngoing: En curso
  incidentOpenedAt: Abierto a las
  incidentClosedAt: Cerrado a las
  incidentViewOnGitHub: Ver y suscribirse en GitHub
  incidentCommentSummary: Publicado el $DATE por $AUTHOR
  incidentBack: ← Regresar a todos los incidentes
  pastIncidents: Incidentes pasados
  pastIncidentsResolved: Resuelto en $MINUTES minutos con $POSTS publicaciones
  liveStatus: Estado en vivo
  overallUptime: "Tiempo de actividad total: $UPTIME"
  overallUptimeTitle: Actividad total
  averageResponseTime: "Tiempo de respuesta promedio: $TIMEms"
  averageResponseTimeTitle: Respuesta promedio
  sevelDayResponseTime: Tiempo de respuesta de 7 días
  responseTimeMs: Tiempo de respuesta (ms)
  up: Activo
  down: Inactivo
  degraded: Degradado
  ms: ms
  loading: Cargando
  navGitHub: GitHub
  footer: 2022 © Ayphu - Todos los derechos reservados.
  rateLimitExceededTitle: Excede el límite de velocidad
  rateLimitExceededIntro: Has superado el número de solicitudes que puedes realizar en una hora, por lo que tendrás que esperar antes de volver a acceder a este sitio web. Alternativamente, puedes agregar un token de acceso personal de GitHub para continuar usando este sitio web.
  rateLimitExceededWhatDoesErrorMean: ¿Qué significa este error?
  rateLimitExceededErrorMeaning: Este sitio web utiliza la API de GitHub para acceder a datos en tiempo real sobre el estado de nuestros sitios web. De manera predeterminada, GitHub permite que cada dirección IP realice 60 solicitudes por hora, las que se ha consumido.
  rateLimitExceededErrorHowCanFix: ¿Cómo puedo arreglarlo?
  rateLimitExceededErrorFix: Puedes esperar otra hora y se restablecerá el límite de tu dirección IP. Como alternativa, puedes agregar tu token de acceso personal de GitHub, que te brinda 5000 solicitudes adicionales por hora.
  rateLimitExceededGeneratePAT: Aprende a generar un token de acceso personal
  rateLimitExceededHasSet: Tienes un token de acceso personal establecido.
  rateLimitExceededRemoveToken: Eliminar token
  rateLimitExceededGitHubPAT: Token de acceso personal de GitHub
  rateLimitExceededCopyPastePAT: Copiar y pegar tu token
  rateLimitExceededSaveToken: Guardar token
  errorTitle: Ocurrió un error
  errorIntro: Ocurrió un error al tratar de obtener los últimos detalles de estado.
  errorText: Puedes intentar de nuevo en unos minutos.
  errorHome: Ir a inicio
  pastScheduledMaintenance: Mantenimiento programado pasado
  scheduledMaintenance: Mantenimiento programado
  scheduledMaintenanceSummaryStarted: Empezó el $DATE por $DURATION minutos
  scheduledMaintenanceSummaryStarts: Empieza el $DATE por $DURATION minutos
  startedAt: Empezó a
  startsAt: Empieza a
  duration: Duración
  durationMin: $DURATION minutos
  incidentCompleted: Completado
  incidentScheduled: Programado
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
